// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOTRqv8m_zHTHBr4wNRWDICj4l82tULS8',
    appId: '1:347714112681:web:19ee164f07c5920689adb8',
    messagingSenderId: '347714112681',
    projectId: 'food-bridge-8a76e',
    authDomain: 'food-bridge-8a76e.firebaseapp.com',
    storageBucket: 'food-bridge-8a76e.firebasestorage.app',
    measurementId: 'G-4E377W9376',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQbx7qDqfjLtbdSwv2d43ScF78aL6jlxQ',
    appId: '1:347714112681:android:0ee1001d69ee323389adb8',
    messagingSenderId: '347714112681',
    projectId: 'food-bridge-8a76e',
    storageBucket: 'food-bridge-8a76e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5j590T4c2QEzzwDy6DJk7YcjAYW4of5M',
    appId: '1:347714112681:ios:10312d3e37b7f74989adb8',
    messagingSenderId: '347714112681',
    projectId: 'food-bridge-8a76e',
    storageBucket: 'food-bridge-8a76e.firebasestorage.app',
    androidClientId: '347714112681-b43luv4ou33iphnckssarlripufg8bp6.apps.googleusercontent.com',
    iosClientId: '347714112681-gobb93egmbj7d4f17n51gk8iv96vathm.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBridgeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5j590T4c2QEzzwDy6DJk7YcjAYW4of5M',
    appId: '1:347714112681:ios:10312d3e37b7f74989adb8',
    messagingSenderId: '347714112681',
    projectId: 'food-bridge-8a76e',
    storageBucket: 'food-bridge-8a76e.firebasestorage.app',
    androidClientId: '347714112681-b43luv4ou33iphnckssarlripufg8bp6.apps.googleusercontent.com',
    iosClientId: '347714112681-gobb93egmbj7d4f17n51gk8iv96vathm.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBridgeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOTRqv8m_zHTHBr4wNRWDICj4l82tULS8',
    appId: '1:347714112681:web:698680a158f9003389adb8',
    messagingSenderId: '347714112681',
    projectId: 'food-bridge-8a76e',
    authDomain: 'food-bridge-8a76e.firebaseapp.com',
    storageBucket: 'food-bridge-8a76e.firebasestorage.app',
    measurementId: 'G-ZYTX36330T',
  );
}
